# Generated by Django 3.1.2 on 2020-11-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201102_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
